POST https://api.fondy.eu/api/checkout/url/ HTTP/1.1
content-type: application/json

{"request":{"order_id":[19],"order_desc":"Оплата курсов:,Первый месяц обучения,Второй месяц обучения,Третий месяц обучения,6 недель обучения","currency":"USD","amount":1200,"merchant_id":1404610,"signature":"065e81b496033abb45aa6386eb80abda6419179b"}}